name: CI
on:
   pull_request:
    branches: [ master ]
   workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore
      - name: publish
        run: dotnet publish ./RestaurantAPI/RestaurantAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: api-artifact
          path: ${{ env.DOTNET_ROOT }}/api
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
    - name: download artifact
      uses: actions/download-artifact@v3.1.1
      with:
          name: api-artifact
    - name: Azure WebApp deploy
      id: deploy-to-azure
      uses: Azure/webapps-deploy@v2
      with:
          app-name:: 'restaurant-aapi-dev'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
