name: CI
on:
   pull_request:
    branches: [ master ]
   workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore
      - name: publish
        run: dotnet publish ./RestaurantAPI/RestaurantAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
      
  deploy-dev:
    runs-on: ubuntu-latest
    needs: nuild
    steps:
    